name: demo

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the demo, and pushes it to `gh-pages`
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        yarn install

    # Build the demo
    - name: Build the demo
      run: |
        yarn build

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
