name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-api-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install
        run: |
          yarn install

      - name: lint
        run: |
          yarn run lint

      - name: format
        run: |
          yarn run lint:format

      - name: test
        run: |
          yarn run test
