name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypresss
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
      - run: npm install
      - run: yarn run lint:format
      - run: yarn run lint
      - run: npm run build
      - run: npm run test:ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          project: ./packages/editor
          component: true
          quiet: true
          record: false
